//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Test.proto
namespace Test
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllTypes")]
  public partial class AllTypes : global::ProtoBuf.IExtensible
  {
    public AllTypes() {}
    
    private double _doubleType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"doubleType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double doubleType
    {
      get { return _doubleType; }
      set { _doubleType = value; }
    }
    private float _floatType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"floatType", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float floatType
    {
      get { return _floatType; }
      set { _floatType = value; }
    }
    private int _int32Type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"int32Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int int32Type
    {
      get { return _int32Type; }
      set { _int32Type = value; }
    }
    private long _int64Type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"int64Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long int64Type
    {
      get { return _int64Type; }
      set { _int64Type = value; }
    }
    private uint _uint32Type;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"uint32Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uint32Type
    {
      get { return _uint32Type; }
      set { _uint32Type = value; }
    }
    private ulong _uint64Type;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"uint64Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uint64Type
    {
      get { return _uint64Type; }
      set { _uint64Type = value; }
    }
    private int _sint32Type;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"sint32Type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int sint32Type
    {
      get { return _sint32Type; }
      set { _sint32Type = value; }
    }
    private long _sint64Type;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"sint64Type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public long sint64Type
    {
      get { return _sint64Type; }
      set { _sint64Type = value; }
    }
    private uint _fixed32Type;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"fixed32Type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint fixed32Type
    {
      get { return _fixed32Type; }
      set { _fixed32Type = value; }
    }
    private ulong _fixed64Type;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"fixed64Type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong fixed64Type
    {
      get { return _fixed64Type; }
      set { _fixed64Type = value; }
    }
    private int _sfixed32Type;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"sfixed32Type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public int sfixed32Type
    {
      get { return _sfixed32Type; }
      set { _sfixed32Type = value; }
    }
    private long _sfixed64Type;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"sfixed64Type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public long sfixed64Type
    {
      get { return _sfixed64Type; }
      set { _sfixed64Type = value; }
    }
    private bool _boolType;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"boolType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool boolType
    {
      get { return _boolType; }
      set { _boolType = value; }
    }
    private string _stringType;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"stringType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string stringType
    {
      get { return _stringType; }
      set { _stringType = value; }
    }
    private byte[] _bytesType;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"bytesType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] bytesType
    {
      get { return _bytesType; }
      set { _bytesType = value; }
    }

    private AllTypes _allTypes = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"allTypes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AllTypes allTypes
    {
      get { return _allTypes; }
      set { _allTypes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RepeatedTypes")]
  public partial class RepeatedTypes : global::ProtoBuf.IExtensible
  {
    public RepeatedTypes() {}
    
    private readonly global::System.Collections.Generic.List<double> _doubleType = new global::System.Collections.Generic.List<double>();
    [global::ProtoBuf.ProtoMember(1, Name=@"doubleType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<double> doubleType
    {
      get { return _doubleType; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _floatType = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(2, Name=@"floatType", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> floatType
    {
      get { return _floatType; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _int32Type = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"int32Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> int32Type
    {
      get { return _int32Type; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _int64Type = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(4, Name=@"int64Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> int64Type
    {
      get { return _int64Type; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _uint32Type = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"uint32Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> uint32Type
    {
      get { return _uint32Type; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _uint64Type = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(6, Name=@"uint64Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> uint64Type
    {
      get { return _uint64Type; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _sint32Type = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"sint32Type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> sint32Type
    {
      get { return _sint32Type; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _sint64Type = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(8, Name=@"sint64Type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<long> sint64Type
    {
      get { return _sint64Type; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _fixed32Type = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(9, Name=@"fixed32Type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<uint> fixed32Type
    {
      get { return _fixed32Type; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _fixed64Type = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(10, Name=@"fixed64Type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<ulong> fixed64Type
    {
      get { return _fixed64Type; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _sfixed32Type = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"sfixed32Type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<int> sfixed32Type
    {
      get { return _sfixed32Type; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _sfixed64Type = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(12, Name=@"sfixed64Type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<long> sfixed64Type
    {
      get { return _sfixed64Type; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _boolType = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(13, Name=@"boolType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> boolType
    {
      get { return _boolType; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _stringType = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(14, Name=@"stringType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> stringType
    {
      get { return _stringType; }
    }
  
    private readonly global::System.Collections.Generic.List<byte[]> _bytesType = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(15, Name=@"bytesType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> bytesType
    {
      get { return _bytesType; }
    }
  
    private readonly global::System.Collections.Generic.List<RepeatedTypes> _repeatedMessage = new global::System.Collections.Generic.List<RepeatedTypes>();
    [global::ProtoBuf.ProtoMember(16, Name=@"repeatedMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RepeatedTypes> repeatedMessage
    {
      get { return _repeatedMessage; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}